version: '3'

services:
  event-store:
    image: postgres:13.5-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 1s
      timeout: 2s
      retries: 15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecom
    ports:
      - 5432:5432

  flyway:
    build: ./services/event-store-db
    container_name: event-store-flyway
    command: migrate
    environment:
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
      FLYWAY_URL: jdbc:postgresql://event-store/ecom
      # Set the passwords for the users here
      FLYWAY_PLACEHOLDERS_ORDER_SERVICE_USER_PASSWORD: password1
      FLYWAY_PLACEHOLDERS_ORDER_PROCESS_MANAGER_USER_PASSWORD: password2
    depends_on:
      event-store:
        condition: service_healthy

  product-service:
    build: ./mocks/product-service
    environment:
      PORT: 8001
    ports:
      - 8001:8001

  order-service:
    build:
      dockerfile: ./order-service/Dockerfile
      context: ./services
    environment:
      PORT: 8000
      DB_HOST: event-store
      DB_USER: order_writer
      DB_PASSWORD: password1
      DB_PORT: 5432
      DB_DATABASE: ecom
      PRODUCT_SERVICE_HOST: http://product-service:8001/v1
    ports:
      - 8000:8000
    depends_on:
      flyway:
        condition: service_completed_successfully
    profiles:
      - with-services

  checkout-pm:
    build:
      dockerfile: ./checkout-pm/Dockerfile
      context: ./services
    environment:
      READER_DB_HOST: event-store
      READER_DB_USER: order_reader
      READER_DB_PASSWORD: password2
      READER_DB_PORT: 5432
      READER_DB_DATABASE: ecom
      WRITER_DB_HOST: event-store
      WRITER_DB_USER: order_writer
      WRITER_DB_PASSWORD: password1
      WRITER_DB_PORT: 5432
      WRITER_DB_DATABASE: ecom
      BATCH_SIZE: 10
    depends_on:
      flyway:
        condition: service_completed_successfully
    profiles:
      - with-services

  client:
    build: ./client
    ports:
      - 8002:80
    depends_on:
      order-service:
        condition: service_started
    profiles:
      - with-services
